//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muni.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        public FUNCIONARIO()
        {
            this.RESOLUCION = new HashSet<RESOLUCION>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public string RUT { get; set; }
        public string PASS { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOP { get; set; }
        public string APELLIDOM { get; set; }
        public string CORREO { get; set; }
        public System.DateTime FECHA_CONTRATO { get; set; }
        public string MOROSO { get; set; }
        public decimal ID_UNIDAD { get; set; }
        public decimal ID_ROL { get; set; }
        public decimal DIAS_ADMINISTRATIVOS { get; set; }
        public decimal DIAS_FERIADO_ANUAL { get; set; }
    
        public virtual ROL ROL { get; set; }
        public virtual UNIDAD_INTERNA UNIDAD_INTERNA { get; set; }
        public virtual ICollection<RESOLUCION> RESOLUCION { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
    }
}
