//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muni.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuniEntities : DbContext
    {
        public MuniEntities()
            : base("name=MuniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FUNCIONARIO> FUNCIONARIO { get; set; }
        public DbSet<PERMISO> PERMISO { get; set; }
        public DbSet<RESOLUCION> RESOLUCION { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<SOLICITUD> SOLICITUD { get; set; }
        public DbSet<TIPO_PERMISO> TIPO_PERMISO { get; set; }
        public DbSet<UNIDAD_INTERNA> UNIDAD_INTERNA { get; set; }
    }
}
