//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muni.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISO
    {
        public PERMISO()
        {
            this.RESOLUCION = new HashSet<RESOLUCION>();
        }
    
        public decimal ID_PERMISO { get; set; }
        public decimal ESTADO { get; set; }
        public string OBSERVACIONES { get; set; }
        public decimal CANTIDAD_DIAS { get; set; }
        public decimal PENDIENTE { get; set; }
        public decimal ID_SOLICITUD { get; set; }
        public decimal COD_VERIFICACION { get; set; }
    
        public virtual SOLICITUD SOLICITUD { get; set; }
        public virtual ICollection<RESOLUCION> RESOLUCION { get; set; }
    }
}
