//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muni.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PERMISO
    {
        public TIPO_PERMISO()
        {
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public decimal ID_TIPO_PERMISO { get; set; }
        public string NOMBRE { get; set; }
        public decimal NRO_DIAS { get; set; }
    
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
    }
}
